name: Deploy to Fly.io with Terraform

on:
  push:
    branches: [main]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  TF_VAR_fly_api_token: ${{ secrets.FLY_API_TOKEN }}
  TF_VAR_app_name: ${{ secrets.FLY_APP_NAME }}
  TF_VAR_fly_org: ${{ secrets.FLY_ORG }}
  TF_VAR_db_url: ${{ secrets.DB_URL }}
  TF_VAR_groq_api: ${{ secrets.GROQ_API }}

jobs:
  deploy:
    name: Deploy FastAPI app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install alembic

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Run Alembic Migrations
        run: |
          flyctl ssh console -C "alembic revision --message "Your migration message"; alembic upgrade head"

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
